//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckUp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAMION()
        {
            this.CARGA = new HashSet<CARGA>();
        }
    
        public string PATENTE { get; set; }
        public string RUT_CONDUCTOR { get; set; }
        public int NRO_RAMPLAS { get; set; }
        public int NRO_EJES { get; set; }
    
        public virtual CONDUCTOR CONDUCTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARGA> CARGA { get; set; }
    }
}
