//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckUp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARGA()
        {
            this.HOJA_DE_RUTA = new HashSet<HOJA_DE_RUTA>();
        }
    
        public int ID_CARGA { get; set; }
        public string PATENTE { get; set; }
        public string ORIGEN_CARGA { get; set; }
        public string DESTINO_CARGA { get; set; }
        public string DESCRIPCION_CARGA { get; set; }
    
        public virtual CAMION CAMION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOJA_DE_RUTA> HOJA_DE_RUTA { get; set; }
    }
}
