//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckUp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASETA_PUERTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CASETA_PUERTO()
        {
            this.HOJA_DE_RUTA = new HashSet<HOJA_DE_RUTA>();
        }
    
        public int ID_CASETA { get; set; }
        public int ID_REGION { get; set; }
        public string DIRECCION_CASETA { get; set; }
        public int TELEFONO_CASETA { get; set; }
    
        public virtual REGION REGION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOJA_DE_RUTA> HOJA_DE_RUTA { get; set; }
    }
}
