//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckUp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CENTRAL()
        {
            this.HOJA_DE_RUTA = new HashSet<HOJA_DE_RUTA>();
        }
    
        public int ID_CENTRAL { get; set; }
        public int ID_COMUNA { get; set; }
        public string DIRECCION_CENTRAL { get; set; }
        public int TELEFONO_CENTRAL { get; set; }
        public string EMAIL_CENTRAL { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOJA_DE_RUTA> HOJA_DE_RUTA { get; set; }
    }
}
