//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckUp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDUCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONDUCTOR()
        {
            this.CAMION = new HashSet<CAMION>();
        }
    
        public string RUT_CONDUCTOR { get; set; }
        public string NOMBRE_CONDUCTOR { get; set; }
        public string APELLIDOPAT_CONDUCTOR { get; set; }
        public string APELLIDOMAT_CONDUCTOR { get; set; }
        public int TELEFONO_CONDUCTOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMION> CAMION { get; set; }
    }
}
