//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckUp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOJA_DE_RUTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOJA_DE_RUTA()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int ID_HOJA { get; set; }
        public int ID_CENTRAL { get; set; }
        public int ID_CASETA { get; set; }
        public int ID_CARGA { get; set; }
        public string INICIO_RUTA { get; set; }
        public string DESTINO_RUTA { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime FECHA_HORA_LLEGADA { get; set; }
    
        public virtual CARGA CARGA { get; set; }
        public virtual CASETA_PUERTO CASETA_PUERTO { get; set; }
        public virtual CENTRAL CENTRAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
