//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckUp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.HOJA_DE_RUTA = new HashSet<HOJA_DE_RUTA>();
        }
    
        public string RUT_USUARIO { get; set; }
        public int ID_ROL { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string APELLIDOPAT_USUARIO { get; set; }
        public string APELLIDOMAT_USUARIO { get; set; }
        public int TELEFONO_USUARIO { get; set; }
        public string CORREO_USUARIO { get; set; }
    
        public virtual ROL ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOJA_DE_RUTA> HOJA_DE_RUTA { get; set; }
    }
}
